require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AbPhonesController do

  # This should return the minimal set of attributes required to create a valid
  # AbPhone. As you add validations to AbPhone, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "abmaster_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AbPhonesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all ab_phones as @ab_phones" do
      ab_phone = AbPhone.create! valid_attributes
      get :index, {}, valid_session
      assigns(:ab_phones).should eq([ab_phone])
    end
  end

  describe "GET show" do
    it "assigns the requested ab_phone as @ab_phone" do
      ab_phone = AbPhone.create! valid_attributes
      get :show, {:id => ab_phone.to_param}, valid_session
      assigns(:ab_phone).should eq(ab_phone)
    end
  end

  describe "GET new" do
    it "assigns a new ab_phone as @ab_phone" do
      get :new, {}, valid_session
      assigns(:ab_phone).should be_a_new(AbPhone)
    end
  end

  describe "GET edit" do
    it "assigns the requested ab_phone as @ab_phone" do
      ab_phone = AbPhone.create! valid_attributes
      get :edit, {:id => ab_phone.to_param}, valid_session
      assigns(:ab_phone).should eq(ab_phone)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AbPhone" do
        expect {
          post :create, {:ab_phone => valid_attributes}, valid_session
        }.to change(AbPhone, :count).by(1)
      end

      it "assigns a newly created ab_phone as @ab_phone" do
        post :create, {:ab_phone => valid_attributes}, valid_session
        assigns(:ab_phone).should be_a(AbPhone)
        assigns(:ab_phone).should be_persisted
      end

      it "redirects to the created ab_phone" do
        post :create, {:ab_phone => valid_attributes}, valid_session
        response.should redirect_to(AbPhone.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ab_phone as @ab_phone" do
        # Trigger the behavior that occurs when invalid params are submitted
        AbPhone.any_instance.stub(:save).and_return(false)
        post :create, {:ab_phone => { "abmaster_id" => "invalid value" }}, valid_session
        assigns(:ab_phone).should be_a_new(AbPhone)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AbPhone.any_instance.stub(:save).and_return(false)
        post :create, {:ab_phone => { "abmaster_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ab_phone" do
        ab_phone = AbPhone.create! valid_attributes
        # Assuming there are no other ab_phones in the database, this
        # specifies that the AbPhone created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AbPhone.any_instance.should_receive(:update).with({ "abmaster_id" => "1" })
        put :update, {:id => ab_phone.to_param, :ab_phone => { "abmaster_id" => "1" }}, valid_session
      end

      it "assigns the requested ab_phone as @ab_phone" do
        ab_phone = AbPhone.create! valid_attributes
        put :update, {:id => ab_phone.to_param, :ab_phone => valid_attributes}, valid_session
        assigns(:ab_phone).should eq(ab_phone)
      end

      it "redirects to the ab_phone" do
        ab_phone = AbPhone.create! valid_attributes
        put :update, {:id => ab_phone.to_param, :ab_phone => valid_attributes}, valid_session
        response.should redirect_to(ab_phone)
      end
    end

    describe "with invalid params" do
      it "assigns the ab_phone as @ab_phone" do
        ab_phone = AbPhone.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AbPhone.any_instance.stub(:save).and_return(false)
        put :update, {:id => ab_phone.to_param, :ab_phone => { "abmaster_id" => "invalid value" }}, valid_session
        assigns(:ab_phone).should eq(ab_phone)
      end

      it "re-renders the 'edit' template" do
        ab_phone = AbPhone.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AbPhone.any_instance.stub(:save).and_return(false)
        put :update, {:id => ab_phone.to_param, :ab_phone => { "abmaster_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ab_phone" do
      ab_phone = AbPhone.create! valid_attributes
      expect {
        delete :destroy, {:id => ab_phone.to_param}, valid_session
      }.to change(AbPhone, :count).by(-1)
    end

    it "redirects to the ab_phones list" do
      ab_phone = AbPhone.create! valid_attributes
      delete :destroy, {:id => ab_phone.to_param}, valid_session
      response.should redirect_to(ab_phones_url)
    end
  end

end
