require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AbReltionshipsController do

  # This should return the minimal set of attributes required to create a valid
  # AbReltionship. As you add validations to AbReltionship, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "abmaster_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AbReltionshipsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all ab_reltionships as @ab_reltionships" do
      ab_reltionship = AbReltionship.create! valid_attributes
      get :index, {}, valid_session
      assigns(:ab_reltionships).should eq([ab_reltionship])
    end
  end

  describe "GET show" do
    it "assigns the requested ab_reltionship as @ab_reltionship" do
      ab_reltionship = AbReltionship.create! valid_attributes
      get :show, {:id => ab_reltionship.to_param}, valid_session
      assigns(:ab_reltionship).should eq(ab_reltionship)
    end
  end

  describe "GET new" do
    it "assigns a new ab_reltionship as @ab_reltionship" do
      get :new, {}, valid_session
      assigns(:ab_reltionship).should be_a_new(AbReltionship)
    end
  end

  describe "GET edit" do
    it "assigns the requested ab_reltionship as @ab_reltionship" do
      ab_reltionship = AbReltionship.create! valid_attributes
      get :edit, {:id => ab_reltionship.to_param}, valid_session
      assigns(:ab_reltionship).should eq(ab_reltionship)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AbReltionship" do
        expect {
          post :create, {:ab_reltionship => valid_attributes}, valid_session
        }.to change(AbReltionship, :count).by(1)
      end

      it "assigns a newly created ab_reltionship as @ab_reltionship" do
        post :create, {:ab_reltionship => valid_attributes}, valid_session
        assigns(:ab_reltionship).should be_a(AbReltionship)
        assigns(:ab_reltionship).should be_persisted
      end

      it "redirects to the created ab_reltionship" do
        post :create, {:ab_reltionship => valid_attributes}, valid_session
        response.should redirect_to(AbReltionship.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ab_reltionship as @ab_reltionship" do
        # Trigger the behavior that occurs when invalid params are submitted
        AbReltionship.any_instance.stub(:save).and_return(false)
        post :create, {:ab_reltionship => { "abmaster_id" => "invalid value" }}, valid_session
        assigns(:ab_reltionship).should be_a_new(AbReltionship)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AbReltionship.any_instance.stub(:save).and_return(false)
        post :create, {:ab_reltionship => { "abmaster_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ab_reltionship" do
        ab_reltionship = AbReltionship.create! valid_attributes
        # Assuming there are no other ab_reltionships in the database, this
        # specifies that the AbReltionship created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AbReltionship.any_instance.should_receive(:update).with({ "abmaster_id" => "1" })
        put :update, {:id => ab_reltionship.to_param, :ab_reltionship => { "abmaster_id" => "1" }}, valid_session
      end

      it "assigns the requested ab_reltionship as @ab_reltionship" do
        ab_reltionship = AbReltionship.create! valid_attributes
        put :update, {:id => ab_reltionship.to_param, :ab_reltionship => valid_attributes}, valid_session
        assigns(:ab_reltionship).should eq(ab_reltionship)
      end

      it "redirects to the ab_reltionship" do
        ab_reltionship = AbReltionship.create! valid_attributes
        put :update, {:id => ab_reltionship.to_param, :ab_reltionship => valid_attributes}, valid_session
        response.should redirect_to(ab_reltionship)
      end
    end

    describe "with invalid params" do
      it "assigns the ab_reltionship as @ab_reltionship" do
        ab_reltionship = AbReltionship.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AbReltionship.any_instance.stub(:save).and_return(false)
        put :update, {:id => ab_reltionship.to_param, :ab_reltionship => { "abmaster_id" => "invalid value" }}, valid_session
        assigns(:ab_reltionship).should eq(ab_reltionship)
      end

      it "re-renders the 'edit' template" do
        ab_reltionship = AbReltionship.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AbReltionship.any_instance.stub(:save).and_return(false)
        put :update, {:id => ab_reltionship.to_param, :ab_reltionship => { "abmaster_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ab_reltionship" do
      ab_reltionship = AbReltionship.create! valid_attributes
      expect {
        delete :destroy, {:id => ab_reltionship.to_param}, valid_session
      }.to change(AbReltionship, :count).by(-1)
    end

    it "redirects to the ab_reltionships list" do
      ab_reltionship = AbReltionship.create! valid_attributes
      delete :destroy, {:id => ab_reltionship.to_param}, valid_session
      response.should redirect_to(ab_reltionships_url)
    end
  end

end
